### ISSUE TITLE
How to create zmat file?

### ISSUE THREAD

**Issue by Dezhao-Huang** [jdevemy/lammps-tools#1]
Hi jdevemy,
I run into your code and find it very useful.
I have tried these examples and also would like to try hexane for my own research purpose.
How can I create the hexane.zmat file, just like the ethanol.zmat file you have in the repository?
Thank you,
Dezhao

**Comment by jdevemy** [comment]
Hi,
You can prepare a file in .xyz format using Avogadro, for example.

Regards,
Julien
